# Copyright 2021, Pavel Dubrova <pashadubrova@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LOCAL_PATH := vendor/sony/loire

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/bin/adsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/adsprpcd \
    $(LOCAL_PATH)/bin/cdsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/cdsprpcd \
    $(LOCAL_PATH)/bin/cnss-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/cnss-daemon \
    $(LOCAL_PATH)/bin/ims_rtp_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/ims_rtp_daemon \
    $(LOCAL_PATH)/bin/imsdatadaemon:$(TARGET_COPY_OUT_VENDOR)/bin/imsdatadaemon \
    $(LOCAL_PATH)/bin/imsqmidaemon:$(TARGET_COPY_OUT_VENDOR)/bin/imsqmidaemon \
    $(LOCAL_PATH)/bin/irsc_util:$(TARGET_COPY_OUT_VENDOR)/bin/irsc_util \
    $(LOCAL_PATH)/bin/mlog_qmi_service:$(TARGET_COPY_OUT_VENDOR)/bin/mlog_qmi_service \
    $(LOCAL_PATH)/bin/msm_irqbalance:$(TARGET_COPY_OUT_VENDOR)/bin/msm_irqbalance \
    $(LOCAL_PATH)/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/bin/netmgrd \
    $(LOCAL_PATH)/bin/pm-proxy:$(TARGET_COPY_OUT_VENDOR)/bin/pm-proxy \
    $(LOCAL_PATH)/bin/pm-service:$(TARGET_COPY_OUT_VENDOR)/bin/pm-service \
    $(LOCAL_PATH)/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/bin/qmuxd \
    $(LOCAL_PATH)/bin/qseecomd:$(TARGET_COPY_OUT_VENDOR)/bin/qseecomd \
    $(LOCAL_PATH)/bin/rmt_storage:$(TARGET_COPY_OUT_VENDOR)/bin/rmt_storage \
    $(LOCAL_PATH)/bin/sct_service:$(TARGET_COPY_OUT_VENDOR)/bin/sct_service \
    $(LOCAL_PATH)/bin/sensors.qcom:$(TARGET_COPY_OUT_VENDOR)/bin/sensors.qcom \
    $(LOCAL_PATH)/bin/ta_qmi_service:$(TARGET_COPY_OUT_VENDOR)/bin/ta_qmi_service \
    $(LOCAL_PATH)/bin/tad_static:$(TARGET_COPY_OUT_VENDOR)/bin/tad_static \
    $(LOCAL_PATH)/bin/tftp_server:$(TARGET_COPY_OUT_VENDOR)/bin/tftp_server \
    $(LOCAL_PATH)/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    $(LOCAL_PATH)/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    $(LOCAL_PATH)/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    $(LOCAL_PATH)/firmware/a530_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b00 \
    $(LOCAL_PATH)/firmware/a530_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b01 \
    $(LOCAL_PATH)/firmware/a530_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b02 \
    $(LOCAL_PATH)/firmware/a530_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.elf \
    $(LOCAL_PATH)/firmware/a530_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.mdt \
    $(LOCAL_PATH)/firmware/a530v1_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pfp.fw \
    $(LOCAL_PATH)/firmware/a530v1_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pm4.fw \
    $(LOCAL_PATH)/firmware/a530v2_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v2_seq.fw2 \
    $(LOCAL_PATH)/firmware/a530v3_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_gpmu.fw2 \
    $(LOCAL_PATH)/firmware/a530v3_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_seq.fw2 \
    $(LOCAL_PATH)/firmware/cmnlib.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b00 \
    $(LOCAL_PATH)/firmware/cmnlib.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b01 \
    $(LOCAL_PATH)/firmware/cmnlib.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b02 \
    $(LOCAL_PATH)/firmware/cmnlib.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b03 \
    $(LOCAL_PATH)/firmware/cmnlib.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.mdt \
    $(LOCAL_PATH)/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    $(LOCAL_PATH)/firmware/fidocrypto.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fidocrypto.b00 \
    $(LOCAL_PATH)/firmware/fidocrypto.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fidocrypto.b01 \
    $(LOCAL_PATH)/firmware/fidocrypto.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fidocrypto.b02 \
    $(LOCAL_PATH)/firmware/fidocrypto.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fidocrypto.b03 \
    $(LOCAL_PATH)/firmware/fidocrypto.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fidocrypto.mdt \
    $(LOCAL_PATH)/firmware/tzattest.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzattest.b00 \
    $(LOCAL_PATH)/firmware/tzattest.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzattest.b01 \
    $(LOCAL_PATH)/firmware/tzattest.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzattest.b02 \
    $(LOCAL_PATH)/firmware/tzattest.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzattest.b03 \
    $(LOCAL_PATH)/firmware/tzattest.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzattest.mdt \
    $(LOCAL_PATH)/firmware/tzfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b00 \
    $(LOCAL_PATH)/firmware/tzfingerprint.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b01 \
    $(LOCAL_PATH)/firmware/tzfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b02 \
    $(LOCAL_PATH)/firmware/tzfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.b03 \
    $(LOCAL_PATH)/firmware/tzfingerprint.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzfingerprint.mdt \
    $(LOCAL_PATH)/firmware/tzhdcp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b00 \
    $(LOCAL_PATH)/firmware/tzhdcp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b01 \
    $(LOCAL_PATH)/firmware/tzhdcp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b02 \
    $(LOCAL_PATH)/firmware/tzhdcp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.b03 \
    $(LOCAL_PATH)/firmware/tzhdcp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzhdcp.mdt \
    $(LOCAL_PATH)/firmware/tzlibasb.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzlibasb.b00 \
    $(LOCAL_PATH)/firmware/tzlibasb.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzlibasb.b01 \
    $(LOCAL_PATH)/firmware/tzlibasb.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzlibasb.b02 \
    $(LOCAL_PATH)/firmware/tzlibasb.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzlibasb.b03 \
    $(LOCAL_PATH)/firmware/tzlibasb.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzlibasb.mdt \
    $(LOCAL_PATH)/firmware/tzsuntory.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzsuntory.b00 \
    $(LOCAL_PATH)/firmware/tzsuntory.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzsuntory.b01 \
    $(LOCAL_PATH)/firmware/tzsuntory.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzsuntory.b02 \
    $(LOCAL_PATH)/firmware/tzsuntory.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzsuntory.b03 \
    $(LOCAL_PATH)/firmware/tzsuntory.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzsuntory.mdt \
    $(LOCAL_PATH)/firmware/tztpm.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tztpm.b00 \
    $(LOCAL_PATH)/firmware/tztpm.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tztpm.b01 \
    $(LOCAL_PATH)/firmware/tztpm.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tztpm.b02 \
    $(LOCAL_PATH)/firmware/tztpm.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tztpm.b03 \
    $(LOCAL_PATH)/firmware/tztpm.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tztpm.mdt \
    $(LOCAL_PATH)/firmware/tzwidevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b00 \
    $(LOCAL_PATH)/firmware/tzwidevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b01 \
    $(LOCAL_PATH)/firmware/tzwidevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b02 \
    $(LOCAL_PATH)/firmware/tzwidevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.b03 \
    $(LOCAL_PATH)/firmware/tzwidevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwidevine.mdt \
    $(LOCAL_PATH)/firmware/tzwvcpybuf.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b00 \
    $(LOCAL_PATH)/firmware/tzwvcpybuf.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b01 \
    $(LOCAL_PATH)/firmware/tzwvcpybuf.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b02 \
    $(LOCAL_PATH)/firmware/tzwvcpybuf.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.b03 \
    $(LOCAL_PATH)/firmware/tzwvcpybuf.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/tzwvcpybuf.mdt \
    $(LOCAL_PATH)/firmware/venus-v1.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.b00 \
    $(LOCAL_PATH)/firmware/venus-v1.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.b01 \
    $(LOCAL_PATH)/firmware/venus-v1.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.b02 \
    $(LOCAL_PATH)/firmware/venus-v1.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.b03 \
    $(LOCAL_PATH)/firmware/venus-v1.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.b04 \
    $(LOCAL_PATH)/firmware/venus-v1.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.mbn \
    $(LOCAL_PATH)/firmware/venus-v1.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus-v1.mdt \
    $(LOCAL_PATH)/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00 \
    $(LOCAL_PATH)/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01 \
    $(LOCAL_PATH)/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02 \
    $(LOCAL_PATH)/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03 \
    $(LOCAL_PATH)/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04 \
    $(LOCAL_PATH)/firmware/venus.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mbn \
    $(LOCAL_PATH)/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt \
    $(LOCAL_PATH)/lib/com.quicinc.cne.api@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/com.quicinc.cne.api@1.0.so \
    $(LOCAL_PATH)/lib/com.quicinc.cne.api@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib/com.quicinc.cne.api@1.1.so \
    $(LOCAL_PATH)/lib/com.quicinc.cne.constants@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/com.quicinc.cne.constants@1.0.so \
    $(LOCAL_PATH)/lib/com.quicinc.cne.constants@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/com.quicinc.cne.constants@2.0.so \
    $(LOCAL_PATH)/lib/com.quicinc.cne.constants@2.1.so:$(TARGET_COPY_OUT_VENDOR)/lib/com.quicinc.cne.constants@2.1.so \
    $(LOCAL_PATH)/lib/com.quicinc.cne.server@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/com.quicinc.cne.server@2.0.so \
    $(LOCAL_PATH)/lib/com.quicinc.cne.server@2.1.so:$(TARGET_COPY_OUT_VENDOR)/lib/com.quicinc.cne.server@2.1.so \
    $(LOCAL_PATH)/lib/com.quicinc.cne.server@2.2.so:$(TARGET_COPY_OUT_VENDOR)/lib/com.quicinc.cne.server@2.2.so \
    $(LOCAL_PATH)/lib/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglSubDriverAndroid.so \
    $(LOCAL_PATH)/lib/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_adreno.so \
    $(LOCAL_PATH)/lib/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/lib/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_adreno.so \
    $(LOCAL_PATH)/lib/egl/libQTapGLES.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libQTapGLES.so \
    $(LOCAL_PATH)/lib/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_adreno.so \
    $(LOCAL_PATH)/lib/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_esx.so \
    $(LOCAL_PATH)/lib/hw/gatekeeper.msm8952.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.msm8952.so \
    $(LOCAL_PATH)/lib/hw/keystore.msm8952.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.msm8952.so \
    $(LOCAL_PATH)/lib/hw/sensors.msm8952.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.msm8952.so \
    $(LOCAL_PATH)/lib/hw/vulkan.msm8952.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vulkan.msm8952.so \
    $(LOCAL_PATH)/lib/rfsa/adsp/libapps_mem_heap.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libapps_mem_heap.so \
    $(LOCAL_PATH)/lib/rfsa/adsp/libdspCV_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libdspCV_skel.so \
    $(LOCAL_PATH)/lib/rfsa/adsp/libfastcvadsp.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libfastcvadsp.so \
    $(LOCAL_PATH)/lib/rfsa/adsp/libfastcvadsp_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libfastcvadsp_skel.so \
    $(LOCAL_PATH)/lib/rfsa/adsp/libobjectMattingApp_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libobjectMattingApp_skel.so \
    $(LOCAL_PATH)/lib/rfsa/adsp/libpanorama_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libpanorama_skel.so \
    $(LOCAL_PATH)/lib/rfsa/adsp/libscveBlobDescriptor_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libscveBlobDescriptor_skel.so \
    $(LOCAL_PATH)/lib/rfsa/adsp/libscveObjectSegmentation_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libscveObjectSegmentation_skel.so \
    $(LOCAL_PATH)/lib/rfsa/adsp/libscveT2T_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libscveT2T_skel.so \
    $(LOCAL_PATH)/lib/rfsa/adsp/libscveTextReco_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libscveTextReco_skel.so \
    $(LOCAL_PATH)/lib/lib-dplmedia.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-dplmedia.so \
    $(LOCAL_PATH)/lib/lib-imscmservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imscmservice.so \
    $(LOCAL_PATH)/lib/lib-imsdpl.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsdpl.so \
    $(LOCAL_PATH)/lib/lib-imsqimf.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsqimf.so \
    $(LOCAL_PATH)/lib/lib-imsrcs-v2.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcs-v2.so \
    $(LOCAL_PATH)/lib/lib-imsrcsbaseimpl.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcsbaseimpl.so \
    $(LOCAL_PATH)/lib/lib-imsxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsxml.so \
    $(LOCAL_PATH)/lib/lib-rtpcommon.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpcommon.so \
    $(LOCAL_PATH)/lib/lib-rtpcore.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpcore.so \
    $(LOCAL_PATH)/lib/lib-rtpdaemoninterface.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpdaemoninterface.so \
    $(LOCAL_PATH)/lib/lib-rtpsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpsl.so \
    $(LOCAL_PATH)/lib/lib-siputility.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-siputility.so \
    $(LOCAL_PATH)/lib/lib-uceservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-uceservice.so \
    $(LOCAL_PATH)/lib/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libC2D2.so \
    $(LOCAL_PATH)/lib/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCB.so \
    $(LOCAL_PATH)/lib/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so \
    $(LOCAL_PATH)/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libQSEEComAPI.so \
    $(LOCAL_PATH)/lib/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriver_adreno.so \
    $(LOCAL_PATH)/lib/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdb-fts.so \
    $(LOCAL_PATH)/lib/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbloader.so \
    $(LOCAL_PATH)/lib/libacdbmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbmapper.so \
    $(LOCAL_PATH)/lib/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbrtac.so \
    $(LOCAL_PATH)/lib/libactuator_bu64747BS2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu64747BS2.so \
    $(LOCAL_PATH)/lib/libactuator_bu64747BS4.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu64747BS4.so \
    $(LOCAL_PATH)/lib/libactuator_lc898214xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_lc898214xd.so \
    $(LOCAL_PATH)/lib/libactuator_lc898217xc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_lc898217xc.so \
    $(LOCAL_PATH)/lib/libactuator_lc898219xi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_lc898219xi.so \
    $(LOCAL_PATH)/lib/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadiertac.so \
    $(LOCAL_PATH)/lib/libadm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadm.so \
    $(LOCAL_PATH)/lib/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadreno_utils.so \
    $(LOCAL_PATH)/lib/libadsp_default_listener.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadsp_default_listener.so \
    $(LOCAL_PATH)/lib/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadsprpc.so \
    $(LOCAL_PATH)/lib/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudcal.so \
    $(LOCAL_PATH)/lib/libaudioalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioalsa.so \
    $(LOCAL_PATH)/lib/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbccQTI.so \
    $(LOCAL_PATH)/lib/libc2d30_bltlib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30_bltlib.so \
    $(LOCAL_PATH)/lib/libcdsp_default_listener.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcdsp_default_listener.so \
    $(LOCAL_PATH)/lib/libcdsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcdsprpc.so \
    $(LOCAL_PATH)/lib/libchromaflash.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromaflash.so \
    $(LOCAL_PATH)/lib/libchromatix_imx214_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx214_common.so \
    $(LOCAL_PATH)/lib/libchromatix_imx214_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx214_cpp_liveshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx214_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx214_cpp_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx214_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx214_cpp_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx214_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx214_cpp_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx214_default_preview_lc898217.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx214_default_preview_lc898217.so \
    $(LOCAL_PATH)/lib/libchromatix_imx214_default_video_lc898217.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx214_default_video_lc898217.so \
    $(LOCAL_PATH)/lib/libchromatix_imx214_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx214_postproc.so \
    $(LOCAL_PATH)/lib/libchromatix_imx214_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx214_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx214_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx214_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx214_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx214_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx219_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_common.so \
    $(LOCAL_PATH)/lib/libchromatix_imx219_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_cpp_liveshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx219_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_cpp_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx219_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_cpp_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx219_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_cpp_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx219_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_default_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx219_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_default_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx219_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_postproc.so \
    $(LOCAL_PATH)/lib/libchromatix_imx219_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx219_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx219_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx241_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx241_common.so \
    $(LOCAL_PATH)/lib/libchromatix_imx241_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx241_cpp_liveshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx241_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx241_cpp_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx241_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx241_cpp_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx241_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx241_cpp_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx241_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx241_default_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx241_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx241_default_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx241_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx241_postproc.so \
    $(LOCAL_PATH)/lib/libchromatix_imx241_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx241_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx241_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx241_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx241_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx241_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx258_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_common.so \
    $(LOCAL_PATH)/lib/libchromatix_imx258_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_cpp_liveshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx258_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_cpp_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx258_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_cpp_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx258_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_cpp_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx258_default_preview_lc898217.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_default_preview_lc898217.so \
    $(LOCAL_PATH)/lib/libchromatix_imx258_default_video_lc898217.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_default_video_lc898217.so \
    $(LOCAL_PATH)/lib/libchromatix_imx258_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_postproc.so \
    $(LOCAL_PATH)/lib/libchromatix_imx258_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx258_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx258_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx300_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_common.so \
    $(LOCAL_PATH)/lib/libchromatix_imx300_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_cpp_liveshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx300_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_cpp_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx300_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_cpp_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx300_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_cpp_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx300_default_preview_bu64747.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_default_preview_bu64747.so \
    $(LOCAL_PATH)/lib/libchromatix_imx300_default_video_bu64747.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_default_video_bu64747.so \
    $(LOCAL_PATH)/lib/libchromatix_imx300_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_postproc.so \
    $(LOCAL_PATH)/lib/libchromatix_imx300_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx300_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx300_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx400_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx400_common.so \
    $(LOCAL_PATH)/lib/libchromatix_imx400_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx400_cpp_liveshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx400_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx400_cpp_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx400_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx400_cpp_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx400_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx400_cpp_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx400_default_preview_bu64747.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx400_default_preview_bu64747.so \
    $(LOCAL_PATH)/lib/libchromatix_imx400_default_video_bu64747.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx400_default_video_bu64747.so \
    $(LOCAL_PATH)/lib/libchromatix_imx400_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx400_postproc.so \
    $(LOCAL_PATH)/lib/libchromatix_imx400_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx400_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx400_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx400_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx486_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx486_common.so \
    $(LOCAL_PATH)/lib/libchromatix_imx486_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx486_cpp_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx486_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx486_cpp_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx486_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx486_postproc.so \
    $(LOCAL_PATH)/lib/libchromatix_imx486_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx486_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_imx486_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx486_video.so \
    $(LOCAL_PATH)/lib/libchromatix_imx486_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx486_zsl_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_imx486_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx486_zsl_video.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k3l6_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l6_common.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k3l6_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l6_cpp_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k3l6_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l6_cpp_video.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k3l6_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l6_postproc.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k3l6_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l6_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k3l6_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l6_video.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k3l6_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l6_zsl_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k3l6_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l6_zsl_video.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k4h7yx_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7yx_common.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k4h7yx_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7yx_cpp_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k4h7yx_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7yx_cpp_video.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k4h7yx_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7yx_postproc.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k4h7yx_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7yx_snapshot.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k4h7yx_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7yx_video.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k4h7yx_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7yx_zsl_preview.so \
    $(LOCAL_PATH)/lib/libchromatix_s5k4h7yx_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7yx_zsl_video.so \
    $(LOCAL_PATH)/lib/libcne.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcne.so \
    $(LOCAL_PATH)/lib/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneapiclient.so \
    $(LOCAL_PATH)/lib/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libconfigdb.so \
    $(LOCAL_PATH)/lib/libdataitems.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdataitems.so \
    $(LOCAL_PATH)/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    $(LOCAL_PATH)/lib/libdisp-aba.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdisp-aba.so \
    $(LOCAL_PATH)/lib/libdisplayqos.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdisplayqos.so \
    $(LOCAL_PATH)/lib/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmfs.so \
    $(LOCAL_PATH)/lib/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmtime.so \
    $(LOCAL_PATH)/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsi_netctrl.so \
    $(LOCAL_PATH)/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so \
    $(LOCAL_PATH)/lib/libdualcameraddm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdualcameraddm.so \
    $(LOCAL_PATH)/lib/libfastcvopt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfastcvopt.so \
    $(LOCAL_PATH)/lib/libfastrpc_utf_stub.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfastrpc_utf_stub.so \
    $(LOCAL_PATH)/lib/libflash_pmic.so:$(TARGET_COPY_OUT_VENDOR)/lib/libflash_pmic.so \
    $(LOCAL_PATH)/lib/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgsl.so \
    $(LOCAL_PATH)/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so \
    $(LOCAL_PATH)/lib/libjpegdhw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdhw.so \
    $(LOCAL_PATH)/lib/libjpegdmahw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdmahw.so \
    $(LOCAL_PATH)/lib/libjpegehw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegehw.so \
    $(LOCAL_PATH)/lib/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-glnext.so \
    $(LOCAL_PATH)/lib/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qcom.so \
    $(LOCAL_PATH)/lib/libloc_pla.so:$(TARGET_COPY_OUT_VENDOR)/lib/libloc_pla.so \
    $(LOCAL_PATH)/lib/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblqe.so \
    $(LOCAL_PATH)/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdmdetect.so \
    $(LOCAL_PATH)/lib/libmiscta.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmiscta.so \
    $(LOCAL_PATH)/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so \
    $(LOCAL_PATH)/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so \
    $(LOCAL_PATH)/lib/libmmcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_frame_algorithm.so \
    $(LOCAL_PATH)/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    $(LOCAL_PATH)/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so \
    $(LOCAL_PATH)/lib/libmmcamera2_is.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_is.so \
    $(LOCAL_PATH)/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    $(LOCAL_PATH)/lib/libmmcamera2_mct.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_mct.so \
    $(LOCAL_PATH)/lib/libmmcamera2_mct_shimlayer.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_mct_shimlayer.so \
    $(LOCAL_PATH)/lib/libmmcamera2_pp_buf_mgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pp_buf_mgr.so \
    $(LOCAL_PATH)/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so \
    $(LOCAL_PATH)/lib/libmmcamera2_q3a_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_q3a_core.so \
    $(LOCAL_PATH)/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    $(LOCAL_PATH)/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_algorithm.so \
    $(LOCAL_PATH)/lib/libmmcamera2_stats_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_lib.so \
    $(LOCAL_PATH)/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    $(LOCAL_PATH)/lib/libmmcamera_chromaflash_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_chromaflash_lib.so \
    $(LOCAL_PATH)/lib/libmmcamera_dbg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dbg.so \
    $(LOCAL_PATH)/lib/libmmcamera_dummyalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dummyalgo.so \
    $(LOCAL_PATH)/lib/libmmcamera_eebinparse.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_eebinparse.so \
    $(LOCAL_PATH)/lib/libmmcamera_eeprom_util.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_eeprom_util.so \
    $(LOCAL_PATH)/lib/libmmcamera_eztune_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_eztune_module.so \
    $(LOCAL_PATH)/lib/libmmcamera_facedetection_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_facedetection_lib.so \
    $(LOCAL_PATH)/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_faceproc.so \
    $(LOCAL_PATH)/lib/libmmcamera_faceproc2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_faceproc2.so \
    $(LOCAL_PATH)/lib/libmmcamera_hdr_gb_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_gb_lib.so \
    $(LOCAL_PATH)/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so \
    $(LOCAL_PATH)/lib/libmmcamera_imglib_faceproc_adspstub.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib_faceproc_adspstub.so \
    $(LOCAL_PATH)/lib/libmmcamera_imglib_faceproc_adspstub2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib_faceproc_adspstub2.so \
    $(LOCAL_PATH)/lib/libmmcamera_imx214.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx214.so \
    $(LOCAL_PATH)/lib/libmmcamera_imx219.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx219.so \
    $(LOCAL_PATH)/lib/libmmcamera_imx241.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx241.so \
    $(LOCAL_PATH)/lib/libmmcamera_imx258.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx258.so \
    $(LOCAL_PATH)/lib/libmmcamera_imx300.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx300.so \
    $(LOCAL_PATH)/lib/libmmcamera_imx400.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx400.so \
    $(LOCAL_PATH)/lib/libmmcamera_imx402.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx402.so \
    $(LOCAL_PATH)/lib/libmmcamera_imx486.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx486.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_abcc44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_abcc44.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_abf40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_abf40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_bcc40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bcc40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_be_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_be_stats44.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_bf_stats47.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bf_stats47.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_bg_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bg_stats44.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_bhist_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bhist_stats44.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_bpc40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bpc40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_chroma_enhan40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_chroma_enhan40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_chroma_suppress40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_chroma_suppress40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_clamp_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_encoder40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_clamp_video40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_video40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_clamp_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_viewfinder40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_color_correct40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_correct40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_color_xform_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_xform_encoder40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_color_xform_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_xform_viewfinder40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_cs_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_cs_stats44.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_demosaic40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_demosaic40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_demux40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_demux40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_fovcrop_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_fovcrop_encoder40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_fovcrop_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_fovcrop_viewfinder40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_gamma40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_gamma40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_ihist_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_ihist_stats44.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_linearization40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_linearization40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_ltm44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_ltm44.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_luma_adaptation40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_luma_adaptation40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_mce40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_mce40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_mesh_rolloff40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_mesh_rolloff40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_rs_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_rs_stats44.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_scaler_encoder44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_scaler_encoder44.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_scaler_viewfinder44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_scaler_viewfinder44.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_sce40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_sce40.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_sub_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_sub_module.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_template.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_template.so \
    $(LOCAL_PATH)/lib/libmmcamera_isp_wb40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_wb40.so \
    $(LOCAL_PATH)/lib/libmmcamera_llvd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_llvd.so \
    $(LOCAL_PATH)/lib/libmmcamera_optizoom_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_optizoom_lib.so \
    $(LOCAL_PATH)/lib/libmmcamera_paaf_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_paaf_lib.so \
    $(LOCAL_PATH)/lib/libmmcamera_pdaf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdaf.so \
    $(LOCAL_PATH)/lib/libmmcamera_pdafcamif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdafcamif.so \
    $(LOCAL_PATH)/lib/libmmcamera_ppbase_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ppbase_module.so \
    $(LOCAL_PATH)/lib/libmmcamera_quadracfa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_quadracfa.so \
    $(LOCAL_PATH)/lib/libmmcamera_s5k3l6.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l6.so \
    $(LOCAL_PATH)/lib/libmmcamera_s5k4h7yx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k4h7yx.so \
    $(LOCAL_PATH)/lib/libmmcamera_stillmore_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_stillmore_lib.so \
    $(LOCAL_PATH)/lib/libmmcamera_sw2d_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sw2d_lib.so \
    $(LOCAL_PATH)/lib/libmmcamera_thread_services.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_thread_services.so \
    $(LOCAL_PATH)/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_algo.so \
    $(LOCAL_PATH)/lib/libmmcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_bg_pca_algo.so \
    $(LOCAL_PATH)/lib/libmmcamera_trueportrait_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_trueportrait_lib.so \
    $(LOCAL_PATH)/lib/libmmcamera_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tuning.so \
    $(LOCAL_PATH)/lib/libmmcamera_tuning_lookup.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tuning_lookup.so \
    $(LOCAL_PATH)/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so \
    $(LOCAL_PATH)/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so \
    $(LOCAL_PATH)/lib/libmmqjpegdma.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpegdma.so \
    $(LOCAL_PATH)/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnetmgr.so \
    $(LOCAL_PATH)/lib/liboptizoom.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboptizoom.so \
    $(LOCAL_PATH)/lib/libpdmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpdmapper.so \
    $(LOCAL_PATH)/lib/libpdnotifier.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpdnotifier.so \
    $(LOCAL_PATH)/lib/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libperipheral_client.so \
    $(LOCAL_PATH)/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_legacy.so \
    $(LOCAL_PATH)/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so \
    $(LOCAL_PATH)/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdp.so \
    $(LOCAL_PATH)/lib/libqisl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqisl.so \
    $(LOCAL_PATH)/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so \
    $(LOCAL_PATH)/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    $(LOCAL_PATH)/lib/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_helper.so \
    $(LOCAL_PATH)/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so \
    $(LOCAL_PATH)/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    $(LOCAL_PATH)/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    $(LOCAL_PATH)/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    $(LOCAL_PATH)/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so \
    $(LOCAL_PATH)/lib/libqmiservices_ext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices_ext.so \
    $(LOCAL_PATH)/lib/libqomx_jpegdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegdec.so \
    $(LOCAL_PATH)/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so \
    $(LOCAL_PATH)/lib/libqomx_jpegenc_pipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc_pipe.so \
    $(LOCAL_PATH)/lib/libqrtr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqrtr.so \
    $(LOCAL_PATH)/lib/libqseed3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqseed3.so \
    $(LOCAL_PATH)/lib/libqsocket.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqsocket.so \
    $(LOCAL_PATH)/lib/libremosaic_daemon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libremosaic_daemon.so \
    $(LOCAL_PATH)/lib/libril-qc-ltedirectdisc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-ltedirectdisc.so \
    $(LOCAL_PATH)/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-qmi-1.so \
    $(LOCAL_PATH)/lib/libril-qc-radioconfig.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-radioconfig.so \
    $(LOCAL_PATH)/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qcril-hook-oem.so \
    $(LOCAL_PATH)/lib/librilqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/librilqmiservices.so \
    $(LOCAL_PATH)/lib/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib/librpmb.so \
    $(LOCAL_PATH)/lib/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno.so \
    $(LOCAL_PATH)/lib/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno_sha1.so \
    $(LOCAL_PATH)/lib/libsdm-color.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsdm-color.so \
    $(LOCAL_PATH)/lib/libsdm-diag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsdm-diag.so \
    $(LOCAL_PATH)/lib/libsdm-disp-vndapis.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsdm-disp-vndapis.so \
    $(LOCAL_PATH)/lib/libsdmextension.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsdmextension.so \
    $(LOCAL_PATH)/lib/libsdsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsdsprpc.so \
    $(LOCAL_PATH)/lib/libsdsprpc_system.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsdsprpc_system.so \
    $(LOCAL_PATH)/lib/libseemore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libseemore.so \
    $(LOCAL_PATH)/lib/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor1.so \
    $(LOCAL_PATH)/lib/libsensor_reg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor_reg.so \
    $(LOCAL_PATH)/lib/libsettings.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsettings.so \
    $(LOCAL_PATH)/lib/libssc_default_listener.so:$(TARGET_COPY_OUT_VENDOR)/lib/libssc_default_listener.so \
    $(LOCAL_PATH)/lib/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libssd.so \
    $(LOCAL_PATH)/lib/libsystem_health_mon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsystem_health_mon.so \
    $(LOCAL_PATH)/lib/libta.so:$(TARGET_COPY_OUT_VENDOR)/lib/libta.so \
    $(LOCAL_PATH)/lib/libtime_genoff.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtime_genoff.so \
    $(LOCAL_PATH)/lib/libtinyxml2_1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtinyxml2_1.so \
    $(LOCAL_PATH)/lib/libubifocus.so:$(TARGET_COPY_OUT_VENDOR)/lib/libubifocus.so \
    $(LOCAL_PATH)/lib/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxml.so \
    $(LOCAL_PATH)/lib/vendor.qti.hardware.radio.am@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.radio.am@1.0.so \
    $(LOCAL_PATH)/lib/vendor.qti.hardware.radio.ims@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.radio.ims@1.0.so \
    $(LOCAL_PATH)/lib/vendor.qti.hardware.radio.lpa@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.radio.lpa@1.0.so \
    $(LOCAL_PATH)/lib/vendor.qti.hardware.radio.qcrilhook@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.radio.qcrilhook@1.0.so \
    $(LOCAL_PATH)/lib/vendor.qti.hardware.radio.qtiradio@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.radio.qtiradio@1.0.so \
    $(LOCAL_PATH)/lib/vendor.qti.hardware.radio.uim@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.radio.uim@1.0.so \
    $(LOCAL_PATH)/lib/vendor.qti.hardware.radio.uim@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.radio.uim@1.1.so \
    $(LOCAL_PATH)/lib/vendor.qti.hardware.radio.uim_remote_client@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.radio.uim_remote_client@1.0.so \
    $(LOCAL_PATH)/lib/vendor.qti.hardware.radio.uim_remote_server@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.radio.uim_remote_server@1.0.so \
    $(LOCAL_PATH)/lib/vendor.qti.imsrtpservice@1.0-service-Impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.imsrtpservice@1.0-service-Impl.so \
    $(LOCAL_PATH)/lib/vendor.qti.imsrtpservice@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.imsrtpservice@1.0.so \
    $(LOCAL_PATH)/lib64/com.quicinc.cne.api@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.api@1.0.so \
    $(LOCAL_PATH)/lib64/com.quicinc.cne.api@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.api@1.1.so \
    $(LOCAL_PATH)/lib64/com.quicinc.cne.constants@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.constants@1.0.so \
    $(LOCAL_PATH)/lib64/com.quicinc.cne.constants@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.constants@2.0.so \
    $(LOCAL_PATH)/lib64/com.quicinc.cne.constants@2.1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.constants@2.1.so \
    $(LOCAL_PATH)/lib64/com.quicinc.cne.server@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.server@2.0.so \
    $(LOCAL_PATH)/lib64/com.quicinc.cne.server@2.1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.server@2.1.so \
    $(LOCAL_PATH)/lib64/com.quicinc.cne.server@2.2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.server@2.2.so \
    $(LOCAL_PATH)/lib64/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/eglSubDriverAndroid.so \
    $(LOCAL_PATH)/lib64/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libEGL_adreno.so \
    $(LOCAL_PATH)/lib64/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/lib64/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv2_adreno.so \
    $(LOCAL_PATH)/lib64/egl/libQTapGLES.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libQTapGLES.so \
    $(LOCAL_PATH)/lib64/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_adreno.so \
    $(LOCAL_PATH)/lib64/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_esx.so \
    $(LOCAL_PATH)/lib64/hw/gatekeeper.msm8952.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.msm8952.so \
    $(LOCAL_PATH)/lib64/hw/keystore.msm8952.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.msm8952.so \
    $(LOCAL_PATH)/lib64/hw/sensors.msm8952.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sensors.msm8952.so \
    $(LOCAL_PATH)/lib64/hw/vulkan.msm8952.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vulkan.msm8952.so \
    $(LOCAL_PATH)/lib64/lib-dplmedia.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-dplmedia.so \
    $(LOCAL_PATH)/lib64/lib-imscmservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imscmservice.so \
    $(LOCAL_PATH)/lib64/lib-imsdpl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsdpl.so \
    $(LOCAL_PATH)/lib64/lib-imsqimf.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsqimf.so \
    $(LOCAL_PATH)/lib64/lib-imsrcs-v2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcs-v2.so \
    $(LOCAL_PATH)/lib64/lib-imsrcsbaseimpl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcsbaseimpl.so \
    $(LOCAL_PATH)/lib64/lib-imsxml.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsxml.so \
    $(LOCAL_PATH)/lib64/lib-rtpcommon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpcommon.so \
    $(LOCAL_PATH)/lib64/lib-rtpcore.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpcore.so \
    $(LOCAL_PATH)/lib64/lib-rtpdaemoninterface.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpdaemoninterface.so \
    $(LOCAL_PATH)/lib64/lib-rtpsl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpsl.so \
    $(LOCAL_PATH)/lib64/lib-siputility.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-siputility.so \
    $(LOCAL_PATH)/lib64/lib-uceservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-uceservice.so \
    $(LOCAL_PATH)/lib64/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libC2D2.so \
    $(LOCAL_PATH)/lib64/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libCB.so \
    $(LOCAL_PATH)/lib64/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOpenCL.so \
    $(LOCAL_PATH)/lib64/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libQSEEComAPI.so \
    $(LOCAL_PATH)/lib64/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libRSDriver_adreno.so \
    $(LOCAL_PATH)/lib64/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdb-fts.so \
    $(LOCAL_PATH)/lib64/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbloader.so \
    $(LOCAL_PATH)/lib64/libacdbmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbmapper.so \
    $(LOCAL_PATH)/lib64/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbrtac.so \
    $(LOCAL_PATH)/lib64/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadiertac.so \
    $(LOCAL_PATH)/lib64/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadreno_utils.so \
    $(LOCAL_PATH)/lib64/libadsp_default_listener.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadsp_default_listener.so \
    $(LOCAL_PATH)/lib64/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadsprpc.so \
    $(LOCAL_PATH)/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaptXHD_encoder.so \
    $(LOCAL_PATH)/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaptX_encoder.so \
    $(LOCAL_PATH)/lib64/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudcal.so \
    $(LOCAL_PATH)/lib64/libaudioalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudioalsa.so \
    $(LOCAL_PATH)/lib64/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbccQTI.so \
    $(LOCAL_PATH)/lib64/libc2d30_bltlib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libc2d30_bltlib.so \
    $(LOCAL_PATH)/lib64/libcdsp_default_listener.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcdsp_default_listener.so \
    $(LOCAL_PATH)/lib64/libcdsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcdsprpc.so \
    $(LOCAL_PATH)/lib64/libcne.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcne.so \
    $(LOCAL_PATH)/lib64/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcneapiclient.so \
    $(LOCAL_PATH)/lib64/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libconfigdb.so \
    $(LOCAL_PATH)/lib64/libdataitems.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdataitems.so \
    $(LOCAL_PATH)/lib64/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdiag.so \
    $(LOCAL_PATH)/lib64/libdisp-aba.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdisp-aba.so \
    $(LOCAL_PATH)/lib64/libdisplayqos.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdisplayqos.so \
    $(LOCAL_PATH)/lib64/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmfs.so \
    $(LOCAL_PATH)/lib64/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmtime.so \
    $(LOCAL_PATH)/lib64/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsi_netctrl.so \
    $(LOCAL_PATH)/lib64/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsutils.so \
    $(LOCAL_PATH)/lib64/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgsl.so \
    $(LOCAL_PATH)/lib64/libhexagon_nn_stub.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhexagon_nn_stub.so \
    $(LOCAL_PATH)/lib64/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libidl.so \
    $(LOCAL_PATH)/lib64/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-glnext.so \
    $(LOCAL_PATH)/lib64/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-qcom.so \
    $(LOCAL_PATH)/lib64/libloc_pla.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libloc_pla.so \
    $(LOCAL_PATH)/lib64/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblqe.so \
    $(LOCAL_PATH)/lib64/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdmdetect.so \
    $(LOCAL_PATH)/lib64/libmiscta.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmiscta.so \
    $(LOCAL_PATH)/lib64/libmmcamera_dbg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera_dbg.so \
    $(LOCAL_PATH)/lib64/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera_faceproc.so \
    $(LOCAL_PATH)/lib64/libmmcamera_faceproc2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera_faceproc2.so \
    $(LOCAL_PATH)/lib64/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnetmgr.so \
    $(LOCAL_PATH)/lib64/libpdmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpdmapper.so \
    $(LOCAL_PATH)/lib64/libpdnotifier.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpdnotifier.so \
    $(LOCAL_PATH)/lib64/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libperipheral_client.so \
    $(LOCAL_PATH)/lib64/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqcci_legacy.so \
    $(LOCAL_PATH)/lib64/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdi.so \
    $(LOCAL_PATH)/lib64/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdp.so \
    $(LOCAL_PATH)/lib64/libqisl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqisl.so \
    $(LOCAL_PATH)/lib64/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi.so \
    $(LOCAL_PATH)/lib64/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_cci.so \
    $(LOCAL_PATH)/lib64/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_helper.so \
    $(LOCAL_PATH)/lib64/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_qmux.so \
    $(LOCAL_PATH)/lib64/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_common_so.so \
    $(LOCAL_PATH)/lib64/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_csi.so \
    $(LOCAL_PATH)/lib64/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_encdec.so \
    $(LOCAL_PATH)/lib64/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmiservices.so \
    $(LOCAL_PATH)/lib64/libqmiservices_ext.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmiservices_ext.so \
    $(LOCAL_PATH)/lib64/libqrtr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqrtr.so \
    $(LOCAL_PATH)/lib64/libqseed3.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqseed3.so \
    $(LOCAL_PATH)/lib64/libqsocket.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqsocket.so \
    $(LOCAL_PATH)/lib64/libril-qc-ltedirectdisc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-ltedirectdisc.so \
    $(LOCAL_PATH)/lib64/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-qmi-1.so \
    $(LOCAL_PATH)/lib64/libril-qc-radioconfig.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-radioconfig.so \
    $(LOCAL_PATH)/lib64/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qcril-hook-oem.so \
    $(LOCAL_PATH)/lib64/librilqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librilqmiservices.so \
    $(LOCAL_PATH)/lib64/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librpmb.so \
    $(LOCAL_PATH)/lib64/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno.so \
    $(LOCAL_PATH)/lib64/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno_sha1.so \
    $(LOCAL_PATH)/lib64/libsdm-color.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsdm-color.so \
    $(LOCAL_PATH)/lib64/libsdm-diag.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsdm-diag.so \
    $(LOCAL_PATH)/lib64/libsdm-disp-vndapis.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsdm-disp-vndapis.so \
    $(LOCAL_PATH)/lib64/libsdmextension.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsdmextension.so \
    $(LOCAL_PATH)/lib64/libsdsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsdsprpc.so \
    $(LOCAL_PATH)/lib64/libsdsprpc_system.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsdsprpc_system.so \
    $(LOCAL_PATH)/lib64/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsensor1.so \
    $(LOCAL_PATH)/lib64/libsensor_reg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsensor_reg.so \
    $(LOCAL_PATH)/lib64/libsettings.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsettings.so \
    $(LOCAL_PATH)/lib64/libssc_default_listener.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libssc_default_listener.so \
    $(LOCAL_PATH)/lib64/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libssd.so \
    $(LOCAL_PATH)/lib64/libsystem_health_mon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsystem_health_mon.so \
    $(LOCAL_PATH)/lib64/libta.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libta.so \
    $(LOCAL_PATH)/lib64/libtime_genoff.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtime_genoff.so \
    $(LOCAL_PATH)/lib64/libtinyxml2_1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtinyxml2_1.so \
    $(LOCAL_PATH)/lib64/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxml.so \
    $(LOCAL_PATH)/lib64/vendor.qti.hardware.radio.am@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.am@1.0.so \
    $(LOCAL_PATH)/lib64/vendor.qti.hardware.radio.ims@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.ims@1.0.so \
    $(LOCAL_PATH)/lib64/vendor.qti.hardware.radio.lpa@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.lpa@1.0.so \
    $(LOCAL_PATH)/lib64/vendor.qti.hardware.radio.qcrilhook@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.qcrilhook@1.0.so \
    $(LOCAL_PATH)/lib64/vendor.qti.hardware.radio.qtiradio@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.qtiradio@1.0.so \
    $(LOCAL_PATH)/lib64/vendor.qti.hardware.radio.uim@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.uim@1.0.so \
    $(LOCAL_PATH)/lib64/vendor.qti.hardware.radio.uim@1.1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.uim@1.1.so \
    $(LOCAL_PATH)/lib64/vendor.qti.hardware.radio.uim_remote_client@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.uim_remote_client@1.0.so \
    $(LOCAL_PATH)/lib64/vendor.qti.hardware.radio.uim_remote_server@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.uim_remote_server@1.0.so \
    $(LOCAL_PATH)/lib64/vendor.qti.imsrtpservice@1.0-service-Impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.imsrtpservice@1.0-service-Impl.so \
    $(LOCAL_PATH)/lib64/vendor.qti.imsrtpservice@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.imsrtpservice@1.0.so \
    $(LOCAL_PATH)/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    $(LOCAL_PATH)/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    $(LOCAL_PATH)/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    $(LOCAL_PATH)/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    $(LOCAL_PATH)/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql
